[package]
name = "linked-bundle-node-map"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2.125"
pastey = "0.2.3"
js-sys = "0.3.103"
web-sys = { 
    version="0.3.103", features = [
        'CanvasRenderingContext2d',
        'CssStyleDeclaration',
        'Document',
        'DomRect',
        'Element', 
        "ErrorEvent", 
        "Event",
        'WheelEvent',
        'HtmlCanvasElement',
        "HtmlImageElement",
        "HtmlDivElement",
        'PointerEvent',
        'Node',
        'Window',
       "ResizeObserver", "ResizeObserverEntry" 
    ] 
}
gloo ={ version="0.12.0",features=['timers']}
wasm-bindgen-futures = "0.4.76"


[dev-dependencies]
approx = "0.5"
wasm-bindgen-test = "0.3.76"

[lib]
crate-type = ["cdylib","rlib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[profile.release]
# Tell LLVM to optimize for size ('z' is most aggressive, 's' is balanced)
opt-level = "z"
#opt-level = "s"

# disable overflow checks
#overflow-checks = false

# disable debug

# Enable Link Time Optimization across all crates
lto = true

# Limit parallel code generation to a single unit for max optimization
codegen-units = 1
#codegen-units = 16

# Strip all debug symbols and info automatically
strip = true

# Terminate immediately on panic to remove stack-unwinding machinery
panic = "abort"
